version: '3.8'

services:
  mindb-server:
    build: .
    container_name: mindb-server-tls
    ports:
      - "8443:8443"  # HTTPS port
      - "80:80"      # HTTP port (for redirect)
    environment:
      # Data directory
      - MINDB_DATA_DIR=/data
      
      # TLS Configuration
      - ENABLE_TLS=true
      - TLS_CERT_FILE=/certs/server.crt
      - TLS_KEY_FILE=/certs/server.key
      - TLS_REDIRECT_HTTP=true
      - TLS_REDIRECT_PORT=80
      
      # Server configuration
      - HTTP_ADDR=:8443
      - READ_TIMEOUT=30s
      - WRITE_TIMEOUT=30s
      - IDLE_TIMEOUT=120s
      
      # Security
      - AUTH_DISABLED=false
      
      # Performance
      - EXEC_CONCURRENCY=32
      - STMT_TIMEOUT_MS=2000
      - TX_IDLE_TIMEOUT_MS=60000
      - MAX_OPEN_TX=100
      - MAX_TX_PER_CLIENT=5
      
      # Logging
      - LOG_LEVEL=info
      - ENABLE_METRICS=true
    volumes:
      - mindb-data:/data
      - ./certs:/certs:ro  # Mount certificates as read-only
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:8443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mindb-data:
    driver: local
